# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "gh-pages" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install dependencies.
        run: pip install jupyter-book==0.14.0 nbclient==0.5.13 ghp-import
      
      # Runs a single command using the runners shell
      - name: Build document via jupyter-book
        run:  jupyter-book build ${{ github.workspace }}/technique_note/
      
      - name: Commit changes and push to `gh-pages` branch.
        run: |
          git config --local user.name ${{ secrets.USER_NAME }}
          git config --local user.email ${{ secrets.USER_MAIL }}
          git add ${{ github.workspace }}/technique_note/_build/
          git commit -m "chore: build & update html content."
          git push origin gh-pages -f

      # Runs a set of commands using the runners shell
      #- name: Deploy document via ghp-import
      #  run: |
      #    ghp-import -n -p -f ${{ github.workspace }}/technique_note/_build/html
